### ISSUE TITLE
lỗi không đăng kí đăng nhập

### ISSUE THREAD

**Issue by TruongHoang03** [TruongHoang03/netflix_clone#1]
| Auth.useCallback[register] | @ | D:\netflix_clone\pages\auth.tsx:44

⨯ TypeError: The "payload" argument must be of type object. Received null
    at frame (node_modules\next\src\server\patch-error-inspect.ts:89:42)
    at getSourcemappedFrameIfPossible (node_modules\next\src\server\patch-error-inspect.ts:179:32)
    at parseAndSourceMap (node_modules\next\src\server\patch-error-inspect.ts:234:23)
    at exit (node_modules\next\src\server\patch-error-inspect.ts:224:32)
    at log (pages\api\register.ts:36:16)
  34 |         });
  35 |         } catch (error) {
> 36 |         console.log(error);
     |                ^

  37 |         return res.status(400).end();
  38 |     }

**Comment by TruongHoang03** [comment]
![register](https://github.com/user-attachments/assets/7fe298c1-2e57-4a32-89b7-bd6f5bc05a8d)
